url: "https://stupied.net"
title: "stupied stuff!"
description: "Website for Stupied's stupid stuff"
keywords: [stupied,art,comics,blog,ocs]

themes:
- id: light
  title: Tres...?
- id: dark
  title: Stu-DYING!

# Build settings
source: public
destination: _site
keep_files:
- pagefind

sass:
  style: compressed
  sourcemap: never
  quiet_deps: true

jekyll-minifier:
  compress_css: false
  compress_javascript: false
  exclude:
  - feed.xml
  - "*.txt"
  
defaults:
  - scope:
      path: about/
    values:
      layout: about

  - scope:
      path: art/
    values:
      layout: art

  - scope:
      type: art
    values:
      layout: art-view

  - scope:
      type: reviews
    values:
      layout: reviews

  - scope:
      type: reviews
      path: "**/f/"
    values:
      category: completed

  - scope:
      type: posts
    values:
      layout: post

  - scope:
      path: comic/*/
    values:
      layout: comic

# Paginate  
pagination:
  enabled: true

# Pagefind Settings
pagefind:
  exclude:
   - ".art-archive-tags > button"
   - "header"
   - "nav"
   - "footer"

# Collection Stuff
collections_dir: snail

collections:
  art:
    output: true
    permalink: /art/p/:path
    sort_by: date
  img:
    output: true
    permalink: /:path
  
  micro:
  posts:
    permalink: /blog/:name_raw