url: "https://stupied.net"
title: "stupied stuff!"
description: "Website for Stupied's stupid stuff"

# Build settings
source: public
destination: _site
keep_files:
- pagefind

exclude:
- "*.base"

sass:
  style: compressed

jekyll-minifier:
  compress_css: false
  compress_javascript: false
  exclude:
  - feed.xml
  - "*.txt"

# Collection Stuff
collections_dir: snail
collections:
  art:
    output: true
    permalink: /art/p/:path
    sort_by: date
  img:
    output: true
    permalink: /:path
    
  # someone pls remind me to make this into their own seperate website ty
  lists:
  reviews:
    output: true
    permalink: /chez/reviews/p/:name_raw
    sort_by: date
  
  micro:
  posts:
    permalink: /blog/:name_raw
  
  templates:
    output: true
    permalink: /code/:path
  
defaults:
  - scope:
      path: art/
    values:
      layout: art

  - scope:
      type: art
    values:
      layout: art-view

  - scope:
      type: reviews
    values:
      layout: reviews

  - scope:
      type: posts
    values:
      layout: post

  - scope:
      path: comic/*/
    values:
      layout: comic
    
  - scope:
      type: templates
    values:
      layout: code-layout

# Paginate  
pagination:
  enabled: true

# Pagefind Settings
pagefind:
  exclude:
   - ".art-archive-tags > button"
   - "header"
   - "nav"
   - "footer"