collections:
  fanart:
    output: true
    permalink: /fanart/p/:path
    sort_by: date
  lists:
  reviews:
    output: true
    permalink: /chez/reviews/p/:name_raw
    sort_by: date

exclude:
- "*.base"

# Plugins
plugins:
  - jekyll-minifier

page_gen:
  # LIBRARY START
  - data: 'site.data.library'
    template: 'library'
    name_expr: "'index'"
    dir_expr:  "'lib/' + record['id']"

  - data: 'site.data.library'
    template: 'library-ext'
    name_expr: "'ext'"
    extension: json
    dir_expr:  "'lib/' + record['id']"
    filter: external
  # LIBRARY END

  # MICROBLOG START
  - data: 'site.data.blog.micro.years'
    template: 'blog-micro'
    name: "year"
    dir:  "/blog/"
  # MICROBLOG END

timezone: Asia/Manila
deploying: true

jekyll_get_json:
  - data: archived
    json: https://archive.stupied.net/main.json
  - data: albums
    json: https://album.stupied.net/ext.json
  - data: templates
    json: https://code.stupied.net/ext.json