collections:
  commission:
    output: true
    permalink: /commission/p/:path
    sort_by: date
  fanart:
    output: true
    permalink: /fanart/p/:path
    sort_by: date
  mii:
    output: true
    permalink: /mii/p/:path
    sort_by: date

  outlinks:
  lists:
  reviews:
    output: true
    permalink: /chez/reviews/p/:name_raw
    sort_by: date

exclude:
- "*.base"

# Plugins
plugins:
  - jekyll-minifier

page_gen:
  # LIBRARY START
  - data: 'site.data.comics'
    template: 'library'
    name_expr: "'index'"
    dir_expr:  "'lib/' + record['id']"

  - data: 'site.data.comics'
    template: 'library-ext'
    name_expr: "'ext'"
    extension: json
    dir_expr:  "'lib/' + record['id']"
    filter: external

  - data: 'site.data.garden'
    template: 'garden'
    name_expr: "'index'"
    dir_expr:  "'lib/' + record['id']"
  # LIBRARY END

timezone: Asia/Manila
deploying: true

jekyll_get_json:
  - data: archived
    json: https://archive.stupied.net/main.json

  - data: albums
    json: https://album.stupied.net/ext.json

  - data: templates
    json: https://code.stupied.net/ext.json

  - data: ocs
    json: https://wiki.stupied.net/ext.json