name: Deploy to Main Neocities and Nekoweb Mirror!

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities-n-nekoweb
  cancel-in-progress: true

env:  
  JEKYLL_ENV: production
  SUPPORTER: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Pagefind
      run: |
        if [ "${SUPPORTER}" = "true" ]; then
          echo "PROTECTED=" >> $GITHUB_ENV
        else
          echo "PROTECTED=**/pagefind/**" >> $GITHUB_ENV
          mv public/_plugins/pagefind.rb pagefind.rb
        fi

    # IMAGE MANIPULATION START
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install imagemagick -y

    - name: Resize Images in Reviews 
      uses: ./.github/actions/resize-images
      with: 
        folder: public/snail/_img/chez/reviews/img/
        dimension: x200
    # IMAGE MANIPULATION END

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'

    - name: Install Jekyll Bundle 
      run: bundle install

    # NEOCITIES BUILD START
    - name: Build site 4 Main Neocities 
      run: bundle exec jekyll build --config _config.yml,cowtools/config/deploy.yml

    - name: Deploy to Main Neocities
      uses: bcomnes/deploy-to-neocities@v3.0.4
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        neocities_supporter: ${{ env.SUPPORTER }}
        protected_files: ${{ env.PROTECTED }} 
        cleanup: true
        dist_dir: _site
    # NEOCITIES BUILD END

    # NEKOWEB BUILD START
    - name: Set Pagefind
      run: |
        if [ "${SUPPORTER}" = "false" ]; then
          mv pagefind.rb public/_plugins/pagefind.rb
        fi

    - name: Clean Previous Build
      run: jekyll clean

    - name: Build website 4 Nekoweb Mirror
      run: |
        mv cowtools/nekoweb/elements.css public/
        bundle exec jekyll build --config _config.yml,cowtools/config/nekoweb.yml,cowtools/config/deploy.yml
        
    - name: modify _site
      run: |
        rm -rf _site/webgardens/
        rm -rf _site/webgarden.html
        
    - name: deploy2nekoweb
      uses: indiefellas/deploy2nekoweb@main
      with:
        nekoweb-api-key: ${{ secrets.NEKOWEB_API_TOKEN }}
        nekoweb-domain: 'stupied.nekoweb.org'
        nekoweb-username: 'stupied'
        directory: '_site'
    # NEKOWEB BUILD END