name: Deploy to Nekoweb Mirror!

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities-n-nekoweb
  cancel-in-progress: true

env:  
  JEKYLL_ENV: production
  SUPPORTER: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # IMAGE MANIPULATION START
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install imagemagick -y

    - name: Run script
      run: ruby resize.rb
    # IMAGE MANIPULATION END

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'

    - name: Install Jekyll Bundle 
      run: bundle install

    # NEKOWEB BUILD START
    - name: Build website 4 Nekoweb Mirror
      run: |
        mv cowtools/nekoweb/elements.scss public/
        bundle exec jekyll build --config _config.yml,cowtools/config/nekoweb.yml,cowtools/config/deploy.yml
        
    - name: modify _site
      run: |
        rm -rf _site/webgardens/
        rm -rf _site/webgarden.html
        
    - name: deploy2nekoweb
      uses: indiefellas/deploy2nekoweb@main
      with:
        nekoweb-api-key: ${{ secrets.NEKOWEB_API_TOKEN }}
        nekoweb-domain: 'stupied.nekoweb.org'
        nekoweb-username: 'stupied'
        directory: '_site'
    # NEKOWEB BUILD END