name: Deploy to Profile Neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities-profile
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update date in File
      run: date >> cowtools/profile/updated.txt

    - name: Deploy to Neocities Profile
      uses: bcomnes/deploy-to-neocities@v3.0.4
      with:
        api_key: ${{ secrets.NEOCITIES_PROFILE_API_TOKEN }}
        dist_dir: cowtools/profile/